### PR TITLE
Add architectures for usage in libxxf86dga

### PR DESCRIPTION
**Pull request by ehfd**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@hmaarrfk Could you merge this PR ASAP? I don't have much time left until things become busy again.

https://github.com/conda-forge/xorg-libxxf86dga-feedstock/pull/1 is dependent on this PR.

**Comment by hmaarrfk** [comment]
pkgw is very active is maintains this feedstock, it isn't the norm for conda-forge/core members to step in so quickly. It removes ownership from the maintains that do the heavy lifting.

**Comment by ehfd** [comment]
OK. Then I will hand this over to @pkgw.
Requesting review.

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@hmaarrfk This is technically a PR that solves a currently outstanding issue plaguing another feedstock, so perhaps an exception can be made if it takes more than a shorter timeframe than normal?

**Comment by hmaarrfk** [comment]
What is the issue? The request to support new architectures? Please be patient with maintainers...

**Comment by ehfd** [comment]
@hmaarrfk Okay, okay alright.

**Comment by ehfd** [comment]
@pkgw 

```
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
provider:
  linux_aarch64: default
  linux_ppc64le: default
```

Please add the above architectures on top of your previous commits, and add me to the maintainers list. This PR collides with previous commits.

**Comment by ehfd** [comment]
@hmaarrfk I need added architectures here for backwards compatibility.

Like: https://github.com/conda-forge/xorg-videoproto-feedstock/pull/9

**Comment by ehfd** [comment]
Moving to https://github.com/conda-forge/xorg-xf86dgaproto-feedstock/pull/5

**Pull request closed without merging**
